# Generated by Django 5.2.5 on 2025-09-01 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe顧客ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, verbose_name='StripeサブスクリプションID')),
                ('status', models.CharField(choices=[('active', 'アクティブ'), ('cancelled', 'キャンセル'), ('expired', '期限切れ'), ('payment_failed', '決済失敗')], default='active', max_length=20, verbose_name='ステータス')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='現在の期間開始日')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='現在の期間終了日')),
                ('amount', models.PositiveIntegerField(default=300, verbose_name='月額料金')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'サブスクリプション',
                'verbose_name_plural': 'サブスクリプション',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe決済ID')),
                ('amount', models.PositiveIntegerField(verbose_name='金額')),
                ('status', models.CharField(choices=[('pending', '処理中'), ('succeeded', '成功'), ('failed', '失敗'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='ステータス')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='決済日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='payments.subscription', verbose_name='サブスクリプション')),
            ],
            options={
                'verbose_name': '決済履歴',
                'verbose_name_plural': '決済履歴',
                'ordering': ['-created_at'],
            },
        ),
    ]
