# Generated by Django 5.2.5 on 2025-09-01 14:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(verbose_name='予約日')),
                ('reservation_time', models.TimeField(verbose_name='予約時間')),
                ('party_size', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='人数')),
                ('notes', models.TextField(blank=True, verbose_name='特記事項')),
                ('status', models.CharField(choices=[('pending', '予約中'), ('confirmed', '確定'), ('cancelled', 'キャンセル'), ('completed', '完了')], default='pending', max_length=20, verbose_name='ステータス')),
                ('contact_phone', models.CharField(blank=True, max_length=15, verbose_name='連絡先電話番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant', verbose_name='店舗')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
                'ordering': ['-reservation_date', '-reservation_time'],
            },
        ),
    ]
