# Generated by Django 5.2.5 on 2025-09-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='NAGOYA MESHI株式会社', max_length=100, verbose_name='会社名')),
                ('address', models.TextField(default='〒460-0008 愛知県名古屋市中区栄3-15-33', verbose_name='住所')),
                ('phone', models.CharField(default='052-123-4567', max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(default='info@nagoyameshi.com', max_length=254, verbose_name='メールアドレス')),
                ('business_hours', models.CharField(default='平日 9:00-18:00', max_length=50, verbose_name='営業時間')),
                ('established', models.CharField(default='2020年4月', max_length=20, verbose_name='設立')),
                ('capital', models.CharField(default='1,000万円', max_length=30, verbose_name='資本金')),
                ('representative', models.CharField(default='名古屋 太郎', max_length=50, verbose_name='代表取締役')),
                ('business_content', models.TextField(default='飲食店情報サイトの運営\nグルメ情報の提供\nレストラン予約サービス', verbose_name='事業内容')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '運営会社情報',
                'verbose_name_plural': '運営会社情報',
            },
        ),
    ]
