# Generated by Django 5.2.5 on 2025-09-01 14:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('postal_code', models.CharField(blank=True, max_length=8, verbose_name='郵便番号')),
                ('address', models.TextField(verbose_name='住所')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='電話番号')),
                ('opening_hours', models.CharField(blank=True, max_length=100, verbose_name='営業時間')),
                ('closed_days', models.CharField(blank=True, max_length=100, verbose_name='定休日')),
                ('budget_min', models.PositiveIntegerField(default=0, help_text='最低予算（円）', validators=[django.core.validators.MinValueValidator(0)], verbose_name='予算下限')),
                ('budget_max', models.PositiveIntegerField(default=5000, help_text='最高予算（円）', validators=[django.core.validators.MinValueValidator(0)], verbose_name='予算上限')),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/', verbose_name='メイン画像')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.category', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': '店舗',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'お気に入り',
                'verbose_name_plural': 'お気に入り',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'restaurant')},
            },
        ),
    ]
